# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e3cae53442d8b2b7b6b2c78728e715722201a3af05320fcd0d3cba3e6d6cf9509ea56333b8ff1473e5bc71d0b4df90696ca0a543997db9b83ff44bab0916add

test:
  secret_key_base: e3c5f132515648d3a56fe06249a5a66d0c836bd00402b6c74ca4672a18d5ba5719f02f19909dd6bf47a47a1f784b32d63148f895818eb2fbbb09b8c51a9e627b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
